when:
  - event: push
    branch: [main]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      tags: true

steps:
  - name: release
    image: node:24
    environment:
      TMPDIR: /tmp
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git config --global --add safe.directory "$CI_WORKSPACE"
      - corepack enable
      - corepack prepare pnpm@10.33.2 --activate
      - pnpm config set store-dir /opt/woodpecker/.pnpm-store
      - pnpm install
      - pnpm exec semantic-release
